name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: gtest
      run: sudo apt-get install libgtest-dev
    - name: Install cmake
      run: sudo apt-get install cmake
    - name: cd
      run: cd /usr/src/gtest
    
    - name: cmake
      run: cmake CMakeLists.txt
      
    - name: make 
      run:  make 
